spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 15MB
  datasource:
    # driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/beenProject
    username: root
    password: green502
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 8db8701db67fd418049f9009a00a6995
            client-secret: 6ardw700GJPLYt81HEcf3BOrIW02p8pX
            clientAuthenticationMethod: client_secret_post
            authorizationGrantType: authorization_code
            #redirectUri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            redirectUri: http://192.168.0.144:5226/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
            clientName: Kakao
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
file:
  base-package: D:/been/download/pics/
app: #속성을 바꿀 수 있는 부분 들은 상수 처럼 쓰기 편하도록 만들어놓음
  jwt:
    secret: akjw4egoiaj409gj2a094jg02984jgasegsegase9024jg09ftglk #JWT를 만들 때 쓰는 키, 길이가 짧으면 에러터짐
    header-scheme-name: Authorization
    token-type: Bearer
    access-token-expiry: 7200000 #단위 : 밀리세컨드 7200000은 7200초(2시간) 엑세스 토큰
    refresh-token-expiry: 1296000000 # 15일 리프레시 토큰
  oauth2:
    authorized-redirect-uris:
      - http://localhost:8080/oauth/redirect
      - http://192.168.0.144:5226/oauth/redirect
      - http://localhost:3000/oauth/redirect
